set lin 200 pages 999
set tim on ti on echo on feedback on
alter session set ddl_lock_timeout=10;
alter session set db_file_multiblock_read_count=128;
spool idx_1.log


CREATE INDEX "SAPIENSPRD"."E301MCRINDICE5" ON "SAPIENSPRD"."E301MCR" ("CODEMP", "CODTNS")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SAPIENSPRD" PARALLEL 1 ;

  ALTER INDEX "SAPIENSPRD"."E301MCRINDICE5" NOPARALLEL;

CREATE INDEX "SAPIENSPRD"."E301MCRINDICE7" ON "SAPIENSPRD"."E301MCR" ("DATMOV", "VLRMOV", "CODTNS", "NUMLOT", "CODFIL", "CODEMP")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 INVISIBLE
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SAPIENSPRD"  PARALLEL 1 ;

  ALTER INDEX "SAPIENSPRD"."E301MCRINDICE7" NOPARALLEL;

CREATE INDEX "SAPIENSPRD"."E301MCRINDICE2" ON "SAPIENSPRD"."E301MCR" ("DATPGT", "CODEMP", "CODFIL")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SAPIENSPRD" PARALLEL 1 ;

  ALTER INDEX "SAPIENSPRD"."E301MCRINDICE2" NOPARALLEL;

CREATE INDEX "SAPIENSPRD"."E301MCRINDICE4" ON "SAPIENSPRD"."E301MCR" ("CODEMP", "FILRLC", "NUMRLC", "TPTRLC", "SEQRLC")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SAPIENSPRD" PARALLEL 1 ;

  ALTER INDEX "SAPIENSPRD"."E301MCRINDICE4" NOPARALLEL;

CREATE INDEX "SAPIENSPRD"."E301MCRINDICE8" ON "SAPIENSPRD"."E301MCR" ("CODFIL", "CODEMP", "DATMOV", "NUMFIX", "CHVLOT")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SAPIENSPRD" PARALLEL 1 ;

  ALTER INDEX "SAPIENSPRD"."E301MCRINDICE8" NOPARALLEL;

CREATE INDEX "SAPIENSPRD"."E301MCRINDICE6" ON "SAPIENSPRD"."E301MCR" ("CODEMP", "FILRLC", "NUMRLC", "TPTRLC", "FORRLC", "SEQMCP")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SAPIENSPRD" PARALLEL 1 ;

ALTER INDEX "SAPIENSPRD"."E301MCRINDICE6" NOPARALLEL;

CREATE INDEX "SAPIENSPRD"."E301MCRINDICE3" ON "SAPIENSPRD"."E301MCR" ("EMPCCO", "NUMCCO", "DATCCO", "SEQCCO")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SAPIENSPRD" PARALLEL 1 ;

  ALTER INDEX "SAPIENSPRD"."E301MCRINDICE3" NOPARALLEL;

CREATE INDEX "SAPIENSPRD"."USU_E301MCR01" ON "SAPIENSPRD"."E301MCR" ("CHVLOT", "CODEMP")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SAPIENSPRD" PARALLEL 1 ;

  ALTER INDEX "SAPIENSPRD"."USU_E301MCR01" NOPARALLEL;


CREATE INDEX "SAPIENSPRD"."E000CIXINDICELOTE" ON "SAPIENSPRD"."E000CIX" ("CODINT", "IDEINT", "NUMLOT")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SAPIENSPRD" PARALLEL 1 ;

  ALTER INDEX "SAPIENSPRD"."E000CIXINDICELOTE" NOPARALLEL;

CREATE UNIQUE INDEX "SAPIENSPRD"."CP_E000CIX" ON "SAPIENSPRD"."E000CIX" ("SEQINT", "CODINT", "IDEINT")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SAPIENSPRD" PARALLEL 1 ;

  ALTER INDEX "SAPIENSPRD"."CP_E000CIX" NOPARALLEL;

CREATE INDEX "SAPIENSPRD"."USU_E000CIX1" ON "SAPIENSPRD"."E000CIX" ("IDEINT", "SEQINT")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SAPIENSPRD" PARALLEL 1 ;

  ALTER INDEX "SAPIENSPRD"."USU_E000CIX1" NOPARALLEL;

spool off;
